// Shared site identity + SEO constants. Single source of truth for the URL,
// names, logo, social profiles, and the publisher entity used across all
// structured data (JSON-LD). Keep in sync with layout.tsx metadataBase.

export const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://pencilerkali.com';
export const SITE_NAME = 'PencilerKali.com';
export const SITE_DESC =
  'বাংলাদেশ, বিদেশ, খেলাধুলা, বিনোদন ও ইসলামিক সংবাদের নির্ভরযোগ্য বাংলা সংবাদমাধ্যম — ২৪/৭ আপডেট।';

// Brand mark generated by /logo (next/og). Used for Organization + publisher logo.
export const LOGO_URL = `${SITE_URL}/logo`;
// Default social-share image generated by app/opengraph-image.tsx.
export const OG_IMAGE_URL = `${SITE_URL}/opengraph-image`;

export const SOCIAL = {
  facebook: 'https://www.facebook.com/profile.php?id=100066384905135',
  youtube: 'https://www.youtube.com/@AMRWorld-gd2sl',
};

// Byline used on every article.
export const AUTHOR_NAME = 'নিজস্ব প্রতিবেদক';

export const CATEGORY_LABEL: Record<string, string> = {
  bangladesh: 'বাংলাদেশ',
  bidesh: 'বিদেশ',
  kheladhula: 'খেলাধুলা',
  binodon: 'বিনোদন',
  islamic: 'ইসলামিক',
};

// Reusable publisher entity for Article/NewsArticle JSON-LD.
export const PUBLISHER = {
  '@type': 'Organization',
  name: SITE_NAME,
  url: SITE_URL,
  logo: { '@type': 'ImageObject', url: LOGO_URL, width: 512, height: 512 },
} as const;
